CREATE TABLE flashcards (
    id SERIAL PRIMARY KEY,
    study_set_id INTEGER NOT NULL REFERENCES study_sets(id),
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
